port: 1000
tls_key: /etc/letsencrypt/live/example.com/privkey.pem
tls_cert: /etc/letsencrypt/live/example.com/cert.pem
node_endpoint: http://localhost:3000
addresses:
  - input-your-address-here
mosaic_id_hex: 6BED913FA20223F8 # symbol.xym
price_per_byte: 1000
